### PR TITLE
Adds FOM for enhanced geothermal systems

### PR DESCRIPTION
**Pull request by LukasFrankenQ**
## Changes proposed in this Pull Request

Very small change, just adding a 2%/year FOM value for enhanced geothermal systems, as used in [this paper](https://www.sciencedirect.com/science/article/pii/S0306261920312551#s0100).

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Data source for new technologies is cleary stated.
- [x] Newly introduced dependencies are added to `environment.yaml` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the GPLv3 license.

### CODE REVIEW

**Comment by euronion** [comment]
Looking good, can you add the processed `outputs/*.csv` files as well to the PR?

**Comment by LukasFrankenQ** [comment]
Jup, good call, done!

**Comment by euronion** [comment]
LGTM

**Comment by LukasFrankenQ** [comment]
Tops, thanks! 😎

**Pull request merged**
