### PR TITLE
Integrate new DEA data for renewable fuels

### PR DESCRIPTION
**Pull request by lisazeyen**
Closes # (if applicable).
#109 
 
## Changes proposed in this Pull Request
update to latest release of DEA for renewable fuels

## TODOs

- [x] get workflow running
- [x] check all changed units
- [x] check: methanol from power changed to methanol from hydrogen, VOM are zero in new data set

## Things changed

- new assumptions for  the following techs `['BioSNG', 'BtL', 'Fischer-Tropsch', 'Haber-Bosch', 'air separation unit',
       'biogas', 'biogas CC', 'biogas plus hydrogen', 'biogas upgrading',
       'biomass-to-methanol', 'electrobiofuels', 'electrolysis',
       'methanolisation']`
- biogas upgrading differentiates in new data set between small and large plant, assume small
- biogas plant differentiates in new data set between small and large plant, assume small
- `'biogas plus hydrogen'` has now VOM data
- methanol from power changed to methanol from hydrogen, VOM are zero in new data set
- units changed 
```
		                                                                old	new
biogas upgrading	VOM	EUR/MWh input	EUR/MWh output
biogas upgrading	investment	EUR/kW input	EUR/kW
```
**Biogas upgrading VOM and investment are now given per output -> This would need to be changed in PyPSA-Eur once we switch to new database [here](https://github.com/PyPSA/pypsa-eur/blob/6c7d79f524dedaff929827fc012c62470a457224/scripts/prepare_sector_network.py#L2179-L2181)**

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Data source for new technologies is cleary stated.
- [x] Newly introduced dependencies are added to `environment.yaml` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the GPLv3 license.

### CODE REVIEW

**Comment by lisazeyen** [comment]
Changes electrolysis
FOM_electrolysis
investment_electrolysis
lifetime_electrolysis

**Comment by lisazeyen** [comment]
Bio SNG
investment_BioSNG

**Comment by lisazeyen** [comment]
BtL
VOM_BtL

**Comment by lisazeyen** [comment]
Fischer-Tropsch
VOM_Fischer-Tropsch

**Comment by lisazeyen** [comment]
Haber-Bosch
investment_Haber-Bosch

**Comment by lisazeyen** [comment]
biogas
FOM_biogas
investment_biogas

**Comment by lisazeyen** [comment]
electrobiofuels
VOM_electrobiofuels

**Comment by lisazeyen** [comment]
Biogas CC
FOM_biogas CC
investment_biogas CC

**Comment by lisazeyen** [comment]
biogas + hydrogen

investment_biogas plus hydrogen
VOM_biogas plus hydrogen

**Comment by lisazeyen** [comment]
biomass-to-methanol
investment_biomass-to-methanol
VOM_biomass-to-methanol

**Comment by lisazeyen** [comment]
methanolisation (now from hydrogen)
- in new data VOM are zero
VOM_methanolisation

**Comment by lisazeyen** [comment]
and something changed with the stores. @pz-max can you tell if the new or the old version has the intended data
parameter `decommissioning`was not in the old data set, and something with the hydrogen storage changed
```
old  investment       Hydrogen-charger       1.181390e+06
                      Hydrogen-discharger    1.146506e+06
     FOM              Hydrogen-charger       4.600000e-01
                      Hydrogen-discharger    4.801000e-01
new  investment       Hydrogen               1.833997e+05
                      Hydrogen-charger       0.000000e+00
                      Hydrogen-discharger    0.000000e+00
     FOM              Hydrogen-charger                inf
                      Hydrogen-discharger             inf
     decommissioning  Lead-Acid              1.554277e+04
                      Lithium-Ion-LFP        2.625803e+03
                      Lithium-Ion-NMC        2.625803e+03
                      Ni-Zn                  0.000000e+00
                      Vanadium-Redox-Flow    2.078150e+04
                      Zn-Air                 0.000000e+00
                      Zn-Br-Flow             0.000000e+00
                      Zn-Br-Nonflow          0.000000e+00
Name: 2020, dtype: float64
```

**Comment by lisazeyen** [comment]
Changes in energy storage database due to newer pandas version will be fixed by @pz-max in a separate PR

**Comment by lisazeyen** [comment]
@martavp just tagging you here to inform you that some tech assumptions will change when this PR is merged

**Comment by martavp** [comment]
super, thanks for taking care of implementing the new version and for tagging me @lisazeyen

**Review by fneum — APPROVED** [review]

**Pull request merged**
