### PR TITLE
Add more technology process efficiencies

### PR DESCRIPTION
**Pull request by euronion**
@nworbmot @lisazeyen Adding new conversion efficiencies like this?

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [x] Data source for new technologies is cleary stated.
- [x] Newly introduced dependencies are added to `environment.yaml` (if applicable).
- [x] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the GPLv3 license.

### CODE REVIEW

**Comment by lisazeyen** [comment]
@euronion looks fine for me. Are you going to add the other technologies to this branch and then we pull them in all together?

**Comment by euronion** [comment]
Yes, that's the idea. I just wanted a confirmation before I spent time to add the other technologies. Thanks!

**Comment by euronion** [comment]
RTR @lisazeyen or @nworbmot

**Comment by lisazeyen** [comment]
Great thanks @euronion!

**Pull request merged**
